apiVersion: apps/v1
kind: Deployment
metadata:
  name: axum-demo
  labels:
    app: axum-demo
spec:
  selector:
    matchLabels:
      app: axum-demo
  template:
    metadata:
      labels:
        app: axum-demo
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        ports:
          - containerPort: 8080
