apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-restful
  labels:
    app: todo-restful
spec:
  selector:
    matchLabels:
      app: todo-restful
  template:
    metadata:
      labels:
        app: todo-restful
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag}}
        ports:
          - containerPort: 8080
